[[plugins]]
package = "@netlify/plugin-gatsby"
# build
[build]
command = "gatsby build"
functions = "functions"
publish = "public"
[build.environment]
AWS_LAMBDA_JS_RUNTIME = "nodejs14.x"
GATSBY_CPU_COUNT = "2"
# redirects
[[redirects]]
from = "http://carloswebdev.netlify.com/*"
status = 301
to = "https://www.carloswebdev.com/:splat"
[[redirects]]
from = "https://carloswebdev.netlify.com/*"
status = 301
to = "https://www.carloswebdev.com/:splat"
