# build
[build]
  publish = "public"
  command = "gatsby build"
[build.environment]
  NODE_OPTIONS = "--max_old_space_size=4096"
# Headers 
[[headers]]
  for = "/static/*"
  [headers.values]
    cache-control = "public, max-age=360000"
# redirects
[[redirects]]
  from = "http://carloswebdev.netlify.com/*"
  to = "https://www.carloswebdev.com/:splat"
  status = 301
  
[[redirects]]
  from = "https://carloswebdev.netlify.com/*"
  to = "https://www.carloswebdev.com/:splat"
  status = 301