backend:
  name: git-gateway
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "homepage"
        fields:
          - {
              label: "Template Key",
              name: templateKey,
              widget: hidden,
              default: "home-page",
            }
          - {
              label: "Excerpt",
              name: excerpt,
              widget: text,
              hint: "Please inform. Max 160 characters. Important for SEO",
            }
          - label: Header Area
            name: headerArea
            widget: object
            fields:
              - label: Hero Image
                name: heroImage
                widget: object
                fields:
                  - {
                      label: Image,
                      name: image,
                      widget: image,
                      hint: "size 1920 x 924",
                    }
                  - {
                      label: Title,
                      name: alt,
                      widget: text,
                      hint: "Please inform. Important for SEO",
                    }
              - label: Hero Image For Mobile
                name: heroImageMobile
                widget: object
                fields:
                  - {
                      label: Image,
                      name: image,
                      widget: image,
                      hint: "size 1920 x 924",
                    }
                  - {
                      label: Title,
                      name: alt,
                      widget: text,
                      hint: "Please inform. Important for SEO",
                    }
              - label: Sidebar Avatar Image
                name: sidebarAvatarImage
                widget: object
                fields:
                  - {
                      label: Image,
                      name: image,
                      widget: image,
                      hint: "size 1920 x 924",
                    }
                  - {
                      label: Title,
                      name: alt,
                      widget: text,
                      hint: "Please inform. Important for SEO",
                    }
          - label: About Area
            name: aboutArea
            widget: object
            fields:
              - label: About Image
                name: aboutImage
                widget: object
                fields:
                  - {
                      label: Image,
                      name: image,
                      widget: image,
                      hint: "size 1920 x 924",
                    }
                  - {
                      label: Title,
                      name: alt,
                      widget: text,
                      hint: "Please inform. Important for SEO",
                    }
          - label: Services Area
            name: servicesArea
            widget: object
            fields:
              - {label: Heading, name: heading,widget: text}
              - {label: Blurb, name: blurb,widget: text}
              - label: Services
                label_singular: Service
                name: serices
                widget: list
                fields:
                  - {label: "Icon Classes", name: iconClasses, widget: string,}
                  - {label: "Service Name", name: serviceName, widget: string,}
                  - {label: "Blurb", name: blurb, widget: text,}
          - label: Hire Area
            name: hireArea
            widget: object
            fields:
              - {label: Heading, name: heading,widget: text}
              - {label: Blurb, name: blurb,widget: text}              
              - label: "Background Image"
                name: hireImage
                widget: object
                fields:
                  - {
                      label: Image,
                      name: image,
                      widget: image,
                      hint: "size 1920 x 902",
                    }
                  - {
                      label: Title,
                      name: alt,
                      widget: text,
                      hint: "Please inform. Important for SEO",
                    }
          - label: Portfolio Area
            name: portfolioArea
            widget: object
            fields:
              - {label: Heading, name: heading,widget: text}
              - {label: Blurb, name: blurb,widget: text}
              - label: Projects
                label_singular: Project
                name: projects
                widget: list
                fields:
                  - label: "Project Image"
                    name: projectImage
                    widget: object
                    fields:
                      - {
                          label: Image,
                          name: image,
                          widget: image,
                          hint: "size 600 x 337",
                        }
                      - {
                          label: Title,
                          name: alt,
                          widget: text,
                          hint: "Please inform. Important for SEO",

                        }
                  - {label: Name, name: name,widget: string}
                  - {label: Github Repository, name: github,widget: string}
                  - {label: Site Url, name: siteUrl,widget: string}
                  - {label: Type, name: type,widget: string}
          - label: Contact Area
            name: contactArea
            widget: object
            fields:
              - {
                  label: "Address",
                  name: address,
                  widget: text
                }              
              - {
                  label: "Phone Number",
                  name: phone,
                  widget: string
                }              
              - {
                  label: "Email Address",
                  name: email,
                  widget: string
                }              
          - label: 404 Area
            name:  notFoundArea
            widget: object
            fields:
              - {label: Heading, name: heading,widget: text}
              - {label: Blurb, name: blurb,widget: text}              
              - label: "Background Image"
                name: notFoundImage
                widget: object
                fields:
                  - {
                      label: Image,
                      name: image,
                      widget: image,
                      hint: "size 1920 x 902",
                    }
                  - {
                      label: Title,
                      name: alt,
                      widget: text,
                      hint: "Please inform. Important for SEO",
                    }            
    editor:
      preview: false

  - name: "general"
    label: "General"
    files:
      - file: "src/general/main-menu.md"
        label: "Main Menu"
        name: "mainMenu"
        fields:
          - label: Menu Items
            label_singular: "Menu Item"
            name: menuItems
            widget: list
            required: false
            fields:
              - { label: Name, name: name, widget: string }
              - {
                  label: Link,
                  name: link,
                  widget: string,
                  required: false,
                  hint: "Relative Path. Example: /about/, /contact/, /services/mindfulness-training/, ect..",
                }
              - label: Sub Menu
                name: subMenu
                widget: object
                required: false
                fields:
                  - label: Sub Menu menuItems
                    label_singular: Sub Menu Item
                    name: subMenuItems
                    widget: list
                    fields:
                      - { label: Name, name: name, widget: string }
                      - {
                          label: Link,
                          name: link,
                          widget: string,
                          required: false,
                          hint: "Relative Path. Example: /about/, /contact/, /services/mindfulness-training/, ect..",
                        }
    editor:
      preview: false
